### ISSUE TITLE
Errors during the build of this project

### ISSUE THREAD

**Issue by cnantch** [WrenSecurity/wrensec-persistit#2]
Hello,
i have some questions for you. When i'am doing a "mvn install"  on the project, i have
those errors:
**CommandLineTest.testCommands**:72 expected:<300> but was:<0>
**CreateAndDeleteVolumeTest.recoverDynamicVolumes:68** Should be only one remainin
g journal file expected:<1> but was:<2>
com.persistit.MVCCPruneBufferTest.testWritePagePrune(com.persistit.MVCCPruneBuff
erTest)
  Run 1: **MVCCPruneBufferTest.testWritePagePrune**:340 Should no more than one MVV
record
  Run 2: **MVCCPruneBufferTest>MVCCTestBase.tearDown**:54 open read claims expected:
<0> but was:<1>

  **RecoveryTest.testRolloverDoesntDeleteLiveTransactions**:219 expected:<0> but was
:<232>

I'm using an Apache Maven 3.5.0 and a JDK 1.7.0_79.
It's very weird.

Could you have an idea what it's about?
 Thank you.

**Comment by Kortanul** [comment]
@cnantch unfortunately, the errors are expected. this fork came from ForgeRock, who took over maintenance for a few versions after Akiban stopped maintaining it. But, ForgeRock made some changes that introduced known test failures; Peter Major from ForgeRock admitted in a forum post that they have had to build this project with `-DskipTests` to avoid the issue.

PersistIt is deprecated in OpenDJ 3.5 -- and has been removed from OpenDJ starting in 4.0. If you're trying to build this because you need it for OpenDJ, then you will need to skip tests.

**Comment by cnantch** [comment]
Thank you for the answer.
